fou:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    host: 114.55.146.90
#    port: 3306
#    database: llmdb
#    username: llmdb
#    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: rgks
    username: root
    password: 68942569
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0